theme: jekyll-theme-minimal
title: WMATA Metro Train Arrivals
logo: https://i0.wp.com/www.sainteldaily.com/wp-content/uploads/2010/02/discoball-e1497290968568.png?fit=407%2C400&ssl=1
description: Easily get DC Metro train arrival times in terminal
show_downloads: true
google_analytics: G-K81ZKBJ7M2
