theme: jekyll-theme-minimal
title: WMATA Metro Train Arrivals
logo: https://raw.githubusercontent.com/m-soro/wmata_dc_metro_train_times_v2/main/files/dc_metro_logo.jpeg
description: The purpose is purpose
show_downloads: true
google_analytics: G-K81ZKBJ7M2
